version: "3"

services:
  main:
    image: itzg/minecraft-server
    environment:
      TYPE: PAPER
      VERSION: 1.20.4
      EULA: "TRUE"
    volumes:
      - "./plugins:/plugins"
    restart: always
    ports:
      - "25565:25565"